"""
openentropy: Your computer is a hardware noise observatory.

Harvests entropy from unconventional hardware sources — clock jitter,
kernel counters, memory timing, GPU scheduling, network latency, and more.

This package requires the compiled Rust extension (built via maturin).
"""

__author__ = "Amenti Labs"

from openentropy.openentropy import (
    EntropyPool,
    detect_available_sources,
    platform_info,
    detect_machine_info,
    run_all_tests,
    calculate_quality_score,
    condition,
    min_entropy_estimate,
    quick_min_entropy,
    quick_shannon,
    grade_min_entropy,
    quick_quality,
    version as _rust_version,
    # Analysis
    full_analysis,
    autocorrelation_profile,
    spectral_analysis,
    bit_bias,
    distribution_stats,
    stationarity_test,
    runs_analysis,
    cross_correlation_matrix,
    pearson_correlation,
    approximate_entropy,
    permutation_entropy,
    anderson_darling,
    # Comparison
    compare,
    aggregate_delta,
    two_sample_tests,
    cliffs_delta,
    temporal_analysis,
    digram_analysis,
    markov_analysis,
    multi_lag_analysis,
    run_length_comparison,
    # Trials
    trial_analysis,
    stouffer_combine,
    calibration_check,
    # Benchmark
    benchmark_sources,
    bench_config_defaults,
    # Record
    SessionWriter,
    record,
    # Sessions
    list_sessions,
    load_session_meta,
    load_session_raw_data,
    # Chaos
    chaos_analysis,
    hurst_exponent,
    lyapunov_exponent,
    correlation_dimension,
    bientropy,
    epiplexity,
    sample_entropy,
    dfa_analysis,
    rqa_analysis,
    bootstrap_hurst,
    rolling_hurst,
    cramer_von_mises,
    ljung_box,
    gap_test,
    statistics_analysis,
    anova,
    kruskal_wallis,
    levene_test,
    power_analysis,
    bonferroni_correction,
    holm_bonferroni_correction,
    change_point_detection,
    anomaly_detection,
    burst_detection,
    shift_detection,
    temporal_drift,
    temporal_analysis_suite,
    inter_session_stability,
    mutual_information,
    phase_coherence,
    cross_sync,
    synchrony_analysis,
    global_event_detection,
    # Dispatcher
    analyze,
    analysis_config,
)

__rust_backend__ = True
__version__ = _rust_version()


def version() -> str:
    return _rust_version()


__all__ = [
    "EntropyPool",
    "detect_available_sources",
    "platform_info",
    "detect_machine_info",
    "run_all_tests",
    "calculate_quality_score",
    "condition",
    "min_entropy_estimate",
    "quick_min_entropy",
    "quick_shannon",
    "grade_min_entropy",
    "quick_quality",
    "version",
    "__version__",
    "__rust_backend__",
    # Analysis
    "full_analysis",
    "autocorrelation_profile",
    "spectral_analysis",
    "bit_bias",
    "distribution_stats",
    "stationarity_test",
    "runs_analysis",
    "cross_correlation_matrix",
    "pearson_correlation",
    "approximate_entropy",
    "permutation_entropy",
    "anderson_darling",
    # Comparison
    "compare",
    "aggregate_delta",
    "two_sample_tests",
    "cliffs_delta",
    "temporal_analysis",
    "digram_analysis",
    "markov_analysis",
    "multi_lag_analysis",
    "run_length_comparison",
    # Trials
    "trial_analysis",
    "stouffer_combine",
    "calibration_check",
    # Benchmark
    "benchmark_sources",
    "bench_config_defaults",
    # Record
    "SessionWriter",
    "record",
    # Sessions
    "list_sessions",
    "load_session_meta",
    "load_session_raw_data",
    # Chaos
    "chaos_analysis",
    "hurst_exponent",
    "lyapunov_exponent",
    "correlation_dimension",
    "bientropy",
    "epiplexity",
    "sample_entropy",
    "dfa_analysis",
    "rqa_analysis",
    "bootstrap_hurst",
    "rolling_hurst",
    "cramer_von_mises",
    "ljung_box",
    "gap_test",
    "statistics_analysis",
    "anova",
    "kruskal_wallis",
    "levene_test",
    "power_analysis",
    "bonferroni_correction",
    "holm_bonferroni_correction",
    "change_point_detection",
    "anomaly_detection",
    "burst_detection",
    "shift_detection",
    "temporal_drift",
    "temporal_analysis_suite",
    "inter_session_stability",
    "mutual_information",
    "phase_coherence",
    "cross_sync",
    "synchrony_analysis",
    "global_event_detection",
    # Dispatcher
    "analyze",
    "analysis_config",
]
